"""Command line entry point: ``python3 -m primesim_dm <command>``."""

import argparse
import json
import os
import sys

from . import config as config_mod
from . import emit
from . import netlist as netlist_mod
from . import spice

__version__ = "0.1.0"


def _err(msg):
    sys.stderr.write("error: %s\n" % msg)
    return 2


def _warn(msg):
    sys.stderr.write("warning: %s\n" % msg)


def _load_models(cfg):
    paths = [e["path"] for e in cfg["models"]["files"]]
    subs, files = spice.scan_files(
        paths,
        follow_includes=cfg["models"]["follow_includes"],
        search_dirs=cfg["models"]["search_dirs"],
        expand_buses=cfg["models"]["expand_buses"],
        warn=_warn)
    return subs, files


# ---------------------------------------------------------------- scan
def cmd_scan(args):
    subs, files = spice.scan_files(
        args.files, follow_includes=args.follow_includes,
        search_dirs=args.search_dir or [], expand_buses=args.expand_buses,
        warn=_warn)
    if args.subckt:
        want = set(s.lower() for s in args.subckt)
        subs = [s for s in subs if s.name.lower() in want]
    if args.json:
        json.dump([s.to_dict() for s in subs], sys.stdout, indent=2)
        sys.stdout.write("\n")
        return 0
    print("scanned %d file(s), found %d subckt(s)" % (len(files), len(subs)))
    for s in subs:
        tag = "" if s.depth == 0 else "  (nested, depth %d)" % s.depth
        print("")
        print("%s  [%s:%d]%s" % (s.name, s.path, s.line, tag))
        print("  ports (%d):" % len(s.ports))
        for i, p in enumerate(s.ports):
            print("    %3d  %s" % (i, p))
        if s.params:
            print("  params: %s" % ", ".join(
                "%s=%s" % kv for kv in sorted(s.params.items())))
    return 0


# ---------------------------------------------------------------- init
_INIT_HEADER = """\
// generated by `primesim_dm init` - edit the naming rules, then run:
//   python3 -m primesim_dm gen %s
// Rules are tried in order; the first match wins.  `{1}` is regex group 1,
// `{port}` / `{inst}` / `{subckt}` are also available, and `|upper` /
// `|lower` / `|int` / `|zfill:N` transform the value.
"""


def cmd_init(args):
    subs, files = spice.scan_files(
        args.files, follow_includes=args.follow_includes,
        search_dirs=args.search_dir or [], warn=_warn)
    if not subs:
        return _err("no .subckt found in %s" % ", ".join(args.files))
    index = netlist_mod.build_index(subs)

    wanted = args.subckt or [s.name for s in subs if s.depth == 0]
    instances = []
    for name in wanted:
        cands = index.get(name.lower())
        if not cands:
            return _err("subckt %r not found" % name)
        sub = cands[0]
        inst = {
            "name": "X" + name.upper()[:12],
            "subckt": sub.name,
            "comment": "%d ports from %s" % (len(sub.ports),
                                             os.path.basename(sub.path)),
            "connect": {},
            "unused": [],
        }
        instances.append(inst)

    cfg = {
        "deck": {
            "title": args.title or "auto deck",
            "output": args.deck or "out.sp",
            "temp": [25],
            "options": ["post"],
            "globals": ["vdd", "vss"],
        },
        "models": {
            "files": [os.path.relpath(f, os.path.dirname(
                os.path.abspath(args.output))) for f in files],
            "follow_includes": args.follow_includes,
        },
        "naming": {
            "case": "keep",
            "bus_style": "keep",
            "default": "same_name",
            "rules": [],
        },
        "supplies": [
            {"net": "vdd", "value": 1.1},
            {"net": "vss", "value": 0},
        ],
        "termination": {
            "auto_terminate_floating": True,
            "default": {"type": "rload", "to": "vss", "value": "1T"},
            "overrides": [],
        },
        "instances": instances,
        "analysis": {"tran": {"step": "1p", "stop": "20n"}},
        "probes": [],
    }

    body = json.dumps(cfg, indent=2)
    text = (_INIT_HEADER % os.path.basename(args.output)) + body + "\n"
    if args.output == "-":
        sys.stdout.write(text)
        return 0
    if os.path.exists(args.output) and not args.force:
        return _err("%s already exists (use --force to overwrite)" % args.output)
    with open(args.output, "w") as fh:
        fh.write(text)
    print("wrote %s (%d instance stub(s))" % (args.output, len(instances)))
    print("next: fill in naming.rules / connect, then "
          "`python3 -m primesim_dm gen %s`" % args.output)
    return 0


# ---------------------------------------------------------------- gen
def _build(cfg_path):
    cfg = config_mod.load(cfg_path)
    subs, files = _load_models(cfg)
    if not subs:
        raise netlist_mod.NetlistError(
            "no .subckt found in the configured model files")
    resolver = netlist_mod.Resolver(cfg, netlist_mod.build_index(subs))
    return cfg, resolver.build(), files


def cmd_gen(args):
    try:
        cfg, nl, files = _build(args.config)
    except (config_mod.ConfigError, netlist_mod.NetlistError,
            spice.SpiceError) as exc:
        return _err(str(exc))

    base_dir = cfg["_base_dir"]
    out_path = args.output or cfg["deck"]["output"]
    if not os.path.isabs(out_path):
        out_path = os.path.join(base_dir, out_path)

    deck = emit.render_deck(cfg, nl, config_path=os.path.abspath(args.config))
    report = emit.render_report(cfg, nl, files)

    if args.stdout:
        sys.stdout.write(deck)
    else:
        parent = os.path.dirname(out_path)
        if parent and not os.path.isdir(parent):
            os.makedirs(parent)
        with open(out_path, "w") as fh:
            fh.write(deck)
        rep_path = out_path + ".report.txt"
        with open(rep_path, "w") as fh:
            fh.write(report)
        print("wrote %s" % out_path)
        print("wrote %s" % rep_path)

    if nl.warnings:
        for w in nl.warnings:
            _warn(w)
        if args.strict:
            return 1
    return 0


def cmd_check(args):
    try:
        cfg, nl, files = _build(args.config)
    except (config_mod.ConfigError, netlist_mod.NetlistError,
            spice.SpiceError) as exc:
        return _err(str(exc))
    sys.stdout.write(emit.render_report(cfg, nl, files))
    if nl.warnings and args.strict:
        return 1
    return 0


# ---------------------------------------------------------------- main
def build_parser():
    p = argparse.ArgumentParser(
        prog="primesim_dm",
        description="Generate PrimeSim decks: include the models, wire the "
                    "ports by naming rule, terminate what is unused.")
    p.add_argument("--version", action="version", version=__version__)
    sub = p.add_subparsers(dest="command")

    s = sub.add_parser("scan", help="list .subckt definitions and their ports")
    s.add_argument("files", nargs="+")
    s.add_argument("--subckt", action="append", help="only this subckt")
    s.add_argument("--follow-includes", action="store_true")
    s.add_argument("--search-dir", action="append")
    s.add_argument("--expand-buses", action="store_true",
                   help="expand DQ[7:0] style declarations into single bits")
    s.add_argument("--json", action="store_true")
    s.set_defaults(func=cmd_scan)

    s = sub.add_parser("init", help="scaffold a config from model files")
    s.add_argument("files", nargs="+")
    s.add_argument("-o", "--output", default="deck.jsonc")
    s.add_argument("--subckt", action="append",
                   help="instantiate only this subckt (repeatable)")
    s.add_argument("--deck", help="deck file the config should produce")
    s.add_argument("--title")
    s.add_argument("--follow-includes", action="store_true")
    s.add_argument("--search-dir", action="append")
    s.add_argument("--force", action="store_true")
    s.set_defaults(func=cmd_init)

    s = sub.add_parser("gen", help="generate the deck from a config")
    s.add_argument("config")
    s.add_argument("-o", "--output", help="override deck.output")
    s.add_argument("--stdout", action="store_true")
    s.add_argument("--strict", action="store_true",
                   help="exit non-zero if there are warnings")
    s.set_defaults(func=cmd_gen)

    s = sub.add_parser("check", help="print the connectivity report only")
    s.add_argument("config")
    s.add_argument("--strict", action="store_true")
    s.set_defaults(func=cmd_check)
    return p


def main(argv=None):
    parser = build_parser()
    args = parser.parse_args(argv)
    if not getattr(args, "func", None):
        parser.print_help()
        return 2
    return args.func(args)
