"""Command line entry point: ``python3 -m primesim_dm <command>``."""

import argparse
import json
import os
import re
import sys

from . import check as check_mod
from . import config as config_mod
from . import deck as deck_mod
from . import emit
from . import netlist as netlist_mod
from . import spice

__version__ = "0.1.0"


def _err(msg):
    sys.stderr.write("error: %s\n" % msg)
    return 2


def _warn(msg):
    sys.stderr.write("warning: %s\n" % msg)


def _load_models(cfg):
    paths = [(e["path"], e.get("section")) for e in cfg["models"]["files"]]
    subs, files = spice.scan_files(
        paths,
        follow_includes=cfg["models"]["follow_includes"],
        search_dirs=cfg["models"]["search_dirs"],
        expand_buses=cfg["models"]["expand_buses"],
        warn=_warn)
    return subs, files


# ---------------------------------------------------------------- scan
def cmd_scan(args):
    subs, files = spice.scan_files(
        args.files, follow_includes=args.follow_includes,
        search_dirs=args.search_dir or [], expand_buses=args.expand_buses,
        warn=_warn)
    if args.subckt:
        want = set(s.lower() for s in args.subckt)
        subs = [s for s in subs if s.name.lower() in want]
    if args.json:
        json.dump([s.to_dict() for s in subs], sys.stdout, indent=2)
        sys.stdout.write("\n")
        return 0
    print("scanned %d file(s), found %d subckt(s)" % (len(files), len(subs)))
    for s in subs:
        tag = "" if s.depth == 0 else "  (nested, depth %d)" % s.depth
        print("")
        print("%s  [%s:%d]%s" % (s.name, s.path, s.line, tag))
        if s.node_names:
            print("  ports (%d), names from *node comments:" % len(s.ports))
            for i, p in enumerate(s.ports):
                print("    %3d  %-6s  %s" % (i, p, s.label(i)))
            for problem in s.annotation_problems():
                print("    ! %s" % problem)
        else:
            print("  ports (%d):" % len(s.ports))
            for i, p in enumerate(s.ports):
                print("    %3d  %s" % (i, p))
        if s.params:
            print("  params: %s" % ", ".join(
                "%s=%s" % kv for kv in sorted(s.params.items())))
    return 0


# ---------------------------------------------------------------- init
_INIT_HEADER = """\
// generated by `primesim_dm init` - edit the naming rules, then run:
//   python3 -m primesim_dm gen %s
// Rules are tried in order; the first match wins.  `{1}` is regex group 1,
// `{port}` / `{inst}` / `{subckt}` are also available, and `|upper` /
// `|lower` / `|int` / `|zfill:N` transform the value.
"""


def cmd_init(args):
    subs, files = spice.scan_files(
        args.files, follow_includes=args.follow_includes,
        search_dirs=args.search_dir or [], warn=_warn)
    if not subs:
        return _err("no .subckt found in %s" % ", ".join(args.files))
    index = netlist_mod.build_index(subs)

    wanted = args.subckt or [s.name for s in subs if s.depth == 0]
    instances = []
    for name in wanted:
        cands = index.get(name.lower())
        if not cands:
            return _err("subckt %r not found" % name)
        sub = cands[0]
        inst = {
            "name": "X" + name.upper()[:12],
            "subckt": sub.name,
            "comment": "%d ports from %s" % (len(sub.ports),
                                             os.path.basename(sub.path)),
            "connect": {},
            "unused": [],
        }
        instances.append(inst)

    cfg = {
        "deck": {
            "title": args.title or "auto deck",
            "output": args.deck or "out.sp",
            "temp": [25],
            "options": ["post"],
            "globals": ["vdd", "vss"],
        },
        "models": {
            "files": [os.path.relpath(f, os.path.dirname(
                os.path.abspath(args.output))) for f in files],
            "follow_includes": args.follow_includes,
        },
        "naming": {
            "case": "keep",
            "bus_style": "keep",
            "default": "same_name",
            "rules": [],
        },
        "supplies": [
            {"net": "vdd", "value": 1.1},
            {"net": "vss", "value": 0},
        ],
        "termination": {
            "auto_terminate_floating": True,
            "default": {"type": "rload", "to": "vss", "value": "1T"},
            "overrides": [],
        },
        "instances": instances,
        "analysis": {"tran": {"step": "1p", "stop": "20n"}},
        "probes": [],
    }

    body = json.dumps(cfg, indent=2)
    text = (_INIT_HEADER % os.path.basename(args.output)) + body + "\n"
    if args.output == "-":
        sys.stdout.write(text)
        return 0
    if os.path.exists(args.output) and not args.force:
        return _err("%s already exists (use --force to overwrite)" % args.output)
    with open(args.output, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print("wrote %s (%d instance stub(s))" % (args.output, len(instances)))
    print("next: fill in naming.rules / connect, then "
          "`python3 -m primesim_dm gen %s`" % args.output)
    return 0


# ---------------------------------------------------------------- gen
def _build(cfg_path):
    cfg = config_mod.load(cfg_path)
    subs, files = _load_models(cfg)
    if not subs:
        raise netlist_mod.NetlistError(
            "no .subckt found in the configured model files")
    resolver = netlist_mod.Resolver(cfg, netlist_mod.build_index(subs))
    return cfg, resolver.build(), files


def cmd_gen(args):
    try:
        cfg, nl, files = _build(args.config)
    except (config_mod.ConfigError, netlist_mod.NetlistError,
            spice.SpiceError) as exc:
        return _err(str(exc))

    base_dir = cfg["_base_dir"]
    out_path = args.output or cfg["deck"]["output"]
    if not os.path.isabs(out_path):
        out_path = os.path.join(base_dir, out_path)

    deck = emit.render_deck(cfg, nl, config_path=os.path.abspath(args.config))
    report = emit.render_report(cfg, nl, files)

    if args.stdout:
        sys.stdout.write(deck)
    else:
        parent = os.path.dirname(out_path)
        if parent and not os.path.isdir(parent):
            os.makedirs(parent)
        with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(deck)
        rep_path = out_path + ".report.txt"
        with open(rep_path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(report)
        print("wrote %s" % out_path)
        print("wrote %s" % rep_path)

    if nl.warnings:
        for w in nl.warnings:
            _warn(w)
        if args.strict:
            return 1
    return 0


def cmd_check(args):
    try:
        cfg, nl, files = _build(args.config)
    except (config_mod.ConfigError, netlist_mod.NetlistError,
            spice.SpiceError) as exc:
        return _err(str(exc))
    sys.stdout.write(emit.render_report(cfg, nl, files))
    if nl.warnings and args.strict:
        return 1
    return 0


# ---------------------------------------------------------------- lint
def cmd_lint(args):
    opaque = args.opaque or None
    if args.opaque and not args.no_default_opaque:
        opaque = list(deck_mod.DEFAULT_OPAQUE) + args.opaque
    elif args.no_default_opaque:
        opaque = args.opaque or []
    dk = deck_mod.read(args.deck,
                       follow_includes=not args.no_includes,
                       search_dirs=args.search_dir or [],
                       opaque=opaque, skip=args.skip or [],
                       max_depth=args.max_depth)
    if not dk.files:
        return _err("could not read any of: %s" % ", ".join(args.deck))
    checker = check_mod.Checker(dk, short_ohms=args.short_ohms,
                                keep_nets=args.keep_net or [],
                                force_connectivity=args.force_connectivity)
    findings = checker.run()
    counts = checker.counts()
    report = check_mod.render(
        dk, findings, counts, verbose=args.verbose,
        limit=0 if args.all else args.limit, summary_only=args.summary)
    sys.stdout.write(report)
    if args.output:
        # the full report, whatever the screen was trimmed to: a saved check
        # is there to be diffed against the next run
        full = check_mod.render(dk, findings, counts, verbose=True, limit=0)
        parent = os.path.dirname(os.path.abspath(args.output))
        if parent and not os.path.isdir(parent):
            os.makedirs(parent)
        with open(args.output, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(full)
        print("wrote %s" % args.output)
    if counts[check_mod.SEV_ERROR]:
        return 1
    if args.strict and counts[check_mod.SEV_WARN]:
        return 1
    return 0


# ---------------------------------------------------------------- terminate
def _read_deck(args):
    opaque = args.opaque or None
    if args.opaque and not args.no_default_opaque:
        opaque = list(deck_mod.DEFAULT_OPAQUE) + args.opaque
    elif args.no_default_opaque:
        opaque = args.opaque or []
    return deck_mod.read(args.deck,
                         follow_includes=not args.no_includes,
                         search_dirs=args.search_dir or [],
                         opaque=opaque, skip=args.skip or [],
                         max_depth=args.max_depth)


def cmd_terminate(args):
    dk = _read_deck(args)
    if not dk.files:
        return _err("could not read any of: %s" % ", ".join(args.deck))
    if dk.missing_includes and not args.force:
        return _err(
            "%d include(s) could not be read, so nets that belong to them "
            "look one-sided. Terminating those would paper over the real "
            "problem - fix the includes, or pass --force if you mean it."
            % len(dk.missing_includes))

    checker = check_mod.Checker(dk, keep_nets=args.keep_net or [])
    floating = checker.floating_nets()
    if args.exclude:
        drop = [re.compile(p) for p in args.exclude]
        floating = [f for f in floating
                    if not any(rx.search(f[0]) for rx in drop)]

    text = check_mod.render_terminations(
        dk, floating, kind="none" if args.nodes_only else args.type,
        value=args.value, value2=args.value2, to=args.to,
        prefix=args.prefix, source=os.path.abspath(args.deck[0]))

    if args.output:
        parent = os.path.dirname(os.path.abspath(args.output))
        if parent and not os.path.isdir(parent):
            os.makedirs(parent)
        with open(args.output, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
        print("wrote %s (%d node(s))" % (args.output, len(floating)))
        print("review it, then add:  .include '%s'" % args.output)
    else:
        sys.stdout.write(text)
    return 0


# ---------------------------------------------------------------- main
def build_parser():
    p = argparse.ArgumentParser(
        prog="primesim_dm",
        description="Generate PrimeSim decks: include the models, wire the "
                    "ports by naming rule, terminate what is unused.")
    p.add_argument("--version", action="version", version=__version__)
    sub = p.add_subparsers(dest="command")

    s = sub.add_parser("scan", help="list .subckt definitions and their ports")
    s.add_argument("files", nargs="+")
    s.add_argument("--subckt", action="append", help="only this subckt")
    s.add_argument("--follow-includes", action="store_true")
    s.add_argument("--search-dir", action="append")
    s.add_argument("--expand-buses", action="store_true",
                   help="expand DQ[7:0] style declarations into single bits")
    s.add_argument("--json", action="store_true")
    s.set_defaults(func=cmd_scan)

    s = sub.add_parser("init", help="scaffold a config from model files")
    s.add_argument("files", nargs="+")
    s.add_argument("-o", "--output", default="deck.jsonc")
    s.add_argument("--subckt", action="append",
                   help="instantiate only this subckt (repeatable)")
    s.add_argument("--deck", help="deck file the config should produce")
    s.add_argument("--title")
    s.add_argument("--follow-includes", action="store_true")
    s.add_argument("--search-dir", action="append")
    s.add_argument("--force", action="store_true")
    s.set_defaults(func=cmd_init)

    s = sub.add_parser("gen", help="generate the deck from a config")
    s.add_argument("config")
    s.add_argument("-o", "--output", help="override deck.output")
    s.add_argument("--stdout", action="store_true")
    s.add_argument("--strict", action="store_true",
                   help="exit non-zero if there are warnings")
    s.set_defaults(func=cmd_gen)

    s = sub.add_parser("lint", help="check an existing deck (.sp) for "
                                    "connectivity and structural errors")
    s.add_argument("deck", nargs="+", help="deck file(s) to check")
    s.add_argument("--no-includes", action="store_true",
                   help="do not follow .include/.lib")
    s.add_argument("--search-dir", action="append")
    s.add_argument("--keep-net", action="append",
                   help="regex of nets to exempt from the floating check")
    s.add_argument("--short-ohms", type=float, default=1e-6,
                   help="resistance at or below which two nets are reported "
                        "as one node (default 1e-6)")
    s.add_argument("-v", "--verbose", action="store_true",
                   help="also show info notes")
    s.add_argument("--opaque", action="append", metavar="REGEX",
                   help="read matching files for their .subckt interfaces "
                        "only, never their insides (default: %s)"
                        % ", ".join(deck_mod.DEFAULT_OPAQUE))
    s.add_argument("--no-default-opaque", action="store_true",
                   help="do not apply the built-in opaque patterns")
    s.add_argument("--skip", action="append", metavar="REGEX",
                   help="do not open matching files at all (PDK model "
                        "libraries and the like)")
    s.add_argument("--max-depth", type=int, metavar="N",
                   help="follow includes at most N levels deep")
    s.add_argument("--force-connectivity", action="store_true",
                   help="run the floating/isolated checks even when includes "
                        "are missing (results will be noisy)")
    s.add_argument("--summary", action="store_true",
                   help="counts per finding kind only, no individual lines")
    s.add_argument("--limit", type=int, default=10,
                   help="max findings to list per kind (default 10)")
    s.add_argument("--all", action="store_true",
                   help="list every finding, no per-kind cap")
    s.add_argument("-o", "--output", metavar="FILE",
                   help="also save the full report (every finding, info "
                        "notes included) to a file")
    s.add_argument("--strict", action="store_true",
                   help="exit non-zero on warnings too")
    s.set_defaults(func=cmd_lint)

    s = sub.add_parser("terminate",
                       help="emit R/C termination lines for the nodes "
                            "nothing else connects to")
    s.add_argument("deck", nargs="+")
    s.add_argument("-o", "--output", metavar="FILE",
                   help="write the .inc here instead of stdout")
    s.add_argument("--type", choices=("rload", "cload", "rc"),
                   default="rload",
                   help="rload: a resistor, cload: a capacitor, rc: both "
                        "(default rload)")
    s.add_argument("--value", default="1T",
                   help="resistance for rload/rc (default 1T)")
    s.add_argument("--value2", default="1f",
                   help="capacitance for cload/rc (default 1f)")
    s.add_argument("--to", default="0",
                   help="net the termination returns to (default 0)")
    s.add_argument("--prefix", default="Rterm_",
                   help="element name prefix (default Rterm_)")
    s.add_argument("--nodes-only", action="store_true",
                   help="just list the nodes, generate no elements")
    s.add_argument("--exclude", action="append", metavar="REGEX",
                   help="leave nets matching this alone (repeatable)")
    s.add_argument("--keep-net", action="append", metavar="REGEX",
                   help="nets to exempt from the floating check (repeatable)")
    s.add_argument("--no-includes", action="store_true")
    s.add_argument("--search-dir", action="append")
    s.add_argument("--opaque", action="append", metavar="REGEX")
    s.add_argument("--no-default-opaque", action="store_true")
    s.add_argument("--skip", action="append", metavar="REGEX")
    s.add_argument("--max-depth", type=int, metavar="N")
    s.add_argument("--force", action="store_true",
                   help="proceed even though includes are missing")
    s.set_defaults(func=cmd_terminate)

    s = sub.add_parser("check", help="print the connectivity report only")
    s.add_argument("config")
    s.add_argument("--strict", action="store_true")
    s.set_defaults(func=cmd_check)
    return p


def main(argv=None):
    parser = build_parser()
    args = parser.parse_args(argv)
    if not getattr(args, "func", None):
        parser.print_help()
        return 2
    return args.func(args)
