"""Deck and connectivity-report rendering."""

import datetime
import os

from . import spice

BANNER = "*" + "=" * 76


def _section(title):
    return ["", "*" + "-" * 76, "* %s" % title, "*" + "-" * 76]


def _quote(path):
    return "'%s'" % path


def render_deck(cfg, nl, config_path=None):
    width = cfg["deck"]["width"]
    out = []
    stamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    out.append(BANNER)
    out.append("* %s" % cfg["deck"]["title"])
    out.append("* generated by primesim-dm-setup at %s" % stamp)
    if config_path:
        out.append("* config: %s" % config_path)
    out.append("* regenerate instead of hand-editing: changes here are lost")
    out.append(BANNER)
    out.append(".title %s" % cfg["deck"]["title"])

    for line in cfg["raw_prepend"]:
        out.append(str(line))

    if cfg["deck"]["options"]:
        out.extend(_section("options"))
        for opt in cfg["deck"]["options"]:
            out.append(".option %s" % opt)
    if cfg["deck"]["temp"]:
        out.append(".temp %s" % " ".join(str(t) for t in cfg["deck"]["temp"]))
    if cfg["deck"]["globals"]:
        out.append(".global %s" % " ".join(str(g) for g in cfg["deck"]["globals"]))

    if cfg["models"]["emit_includes"] and cfg["models"]["files"]:
        out.extend(_section("model / library includes"))
        for entry in cfg["models"]["files"]:
            path = entry["path"]
            if entry.get("as") == "skip":
                continue
            if entry.get("section"):
                out.append(".lib %s %s" % (_quote(path), entry["section"]))
            else:
                out.append(".include %s" % _quote(path))

    if cfg["supplies"]:
        out.extend(_section("supplies"))
        for sup in cfg["supplies"]:
            name = sup.get("name") or ("V" + str(sup["net"]).replace("!", ""))
            ref = str(sup.get("ref", "0"))
            val = sup.get("value", 0)
            if isinstance(val, (int, float)):
                val = "DC %s" % val
            out.append("%s %s %s %s" % (name, sup["net"], ref, val))

    out.extend(_section("instances"))
    for inst, sub, bindings in nl.instances:
        out.append("* %s : %s  (%s)" % (inst["name"], sub.name,
                                        os.path.basename(sub.path)))
        if inst.get("comment"):
            out.append("* %s" % inst["comment"])
        toks = [inst["name"]]
        toks.extend(b.net for b in bindings)
        toks.append(sub.name)
        for k, v in sorted((inst.get("params") or {}).items()):
            toks.append("%s=%s" % (k, v))
        out.extend(spice.wrap(toks, width=width))

    if nl.term_elements:
        out.extend(_section("terminations (auto)"))
        for el in nl.term_elements:
            out.append("%s %s %s $ %s"
                       % (el.name, " ".join(el.nodes), el.value, el.comment))

    if cfg["stimulus"]:
        out.extend(_section("stimulus"))
        out.extend(str(s) for s in cfg["stimulus"])

    ana = cfg["analysis"] or {}
    if ana:
        out.extend(_section("analysis"))
        if "op" in ana:
            out.append(".op")
        tr = ana.get("tran")
        if tr:
            if isinstance(tr, str):
                out.append(".tran %s" % tr)
            else:
                line = ".tran %s %s" % (tr["step"], tr["stop"])
                if tr.get("start"):
                    line += " start=%s" % tr["start"]
                if tr.get("extra"):
                    line += " %s" % tr["extra"]
                out.append(line)
        dc = ana.get("dc")
        if dc:
            out.append(".dc %s" % (dc if isinstance(dc, str) else
                                   "%s %s %s %s" % (dc["source"], dc["start"],
                                                    dc["stop"], dc["step"])))
        ac = ana.get("ac")
        if ac:
            out.append(".ac %s" % (ac if isinstance(ac, str) else
                                   "%s %s %s %s" % (ac.get("mode", "dec"),
                                                    ac["points"], ac["start"],
                                                    ac["stop"])))
        for extra in ana.get("raw", []) or []:
            out.append(str(extra))

    if cfg["probes"]:
        out.extend(_section("probes"))
        for p in cfg["probes"]:
            out.append(".probe %s" % p if not str(p).startswith(".") else str(p))
    if cfg["measures"]:
        out.extend(_section("measures"))
        for m in cfg["measures"]:
            out.append(str(m) if str(m).lower().startswith(".meas")
                       else ".meas %s" % m)

    for line in cfg["raw_append"]:
        out.append(str(line))

    out.append("")
    out.append(".end")
    out.append("")
    return "\n".join(out)


def render_report(cfg, nl, subckt_files):
    out = []
    out.append("primesim-dm-setup connectivity report")
    out.append("=" * 60)
    out.append("deck   : %s" % cfg["deck"]["output"])
    out.append("models : %d file(s)" % len(subckt_files))
    for f in subckt_files:
        out.append("         %s" % f)
    out.append("")

    total = 0
    termed = 0
    for inst, sub, bindings in nl.instances:
        out.append("-" * 60)
        out.append("%s  (subckt %s, %d ports)  [%s]"
                   % (inst["name"], sub.name, len(bindings),
                      os.path.basename(sub.path)))
        widest = max([len(b.port) for b in bindings] + [4])
        for b in bindings:
            total += 1
            mark = ""
            if b.terminated:
                termed += 1
                mark = "  <TERM %s>" % (b.term or {}).get("type", "?")
            out.append("  %-*s -> %-24s %-16s %s%s"
                       % (widest, b.port, b.net, b.origin, b.detail, mark))
    out.append("-" * 60)
    out.append("ports: %d total, %d terminated" % (total, termed))

    singles = [(n, u) for n, u in sorted(nl.net_users.items()) if len(u) < 2]
    out.append("nets : %d" % len(nl.net_users))
    if singles:
        out.append("")
        out.append("single-connection nets (check these):")
        for n, u in singles:
            note = "  [open by design]" if n in nl.open_nets else ""
            out.append("  %-28s only %s%s" % (n, u[0], note))

    if nl.warnings:
        out.append("")
        out.append("warnings:")
        for w in nl.warnings:
            out.append("  ! %s" % w)
    out.append("")
    return "\n".join(out)
